pairs:
  - EURUSD
  - GBPUSD
  - USDJPY
  - USDCHF
  - USDCAD
  - AUDUSD
  - NZDUSD
  - EURGBP
  - EURJPY
  - EURCHF
  - EURCAD
  - EURAUD
  - EURNZD
  - GBPJPY
  - GBPCHF
  - GBPCAD
  - GBPAUD
  - GBPNZD
  - CHFJPY
  - CADJPY
  - AUDJPY
  - NZDJPY
  - AUDCAD
  - AUDCHF
  - AUDNZD
  - CADCHF
  - NZDCAD
  - NZDCHF
