name: Deploy dashboard

on:
  workflow_run:
    workflows: ["Umbra Bancii – cron 60m"]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ⚠️  Descărcăm artefactul din CEL MAI RECENT run SUCCES al workflow‑ului principal
      - name: Download fusion artifact from main workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: umbrella_cron.yml                  # fișierul principal
          name: reports-pattern_fusion                 # numele artefactului
          branch: main
          workflow_conclusion: success
          path: site                                   # îl salvăm în folderul site/

      # construim pagina HTML
      - name: Build index.html
        run: |
          cd site
          latest=$(ls -1 PATTERN_FUSION_*.yaml | tail -1)
          {
            echo '<!doctype html><html><head><meta charset="utf-8"><title>Umbra Bancii – Dashboard</title>'
            echo '<style>body{font-family:Arial,Helvetica,sans-serif;margin:40px;}pre{background:#f7f7f7;border:1px solid #ddd;padding:15px;}h1{color:#2050ff}</style></head><body>'
            echo "<h1>Umbra Băncii – Verdict live</h1>"
            echo "<p><strong>Fișier:</strong> $latest</p><pre>"
            cat "$latest"
            echo "</pre><p>Last update: $(date -u '+%Y-%m-%d %H:%M UTC')</p></body></html>"
          } > index.html

      # publicăm pe gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: site
          force_orphan: true
